// tsboard/src/components/ImageWindow.tsx
import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import SampleImage01 from '../assets/images/sample_01.jpg'
import * as fabric from 'fabric'

function ImageWindow({ imageUrl = SampleImage01 }) {
  const canvasWindowRef = useRef<HTMLDivElement>(null)
  const canvasNodeRef = useRef<HTMLCanvasElement>(null)
  const canvasRef = useRef<fabric.Canvas>()
  const zoomInputRef = useRef<HTMLInputElement>(null)

  useLayoutEffect(() => {
    initCanvas()
    document.addEventListener('wheel', handlePanZoom, { passive: false })

    return () => {
      canvasRef.current?.dispose()
      document.removeEventListener('wheel', handlePanZoom)
    }
  }, [])

  const initCanvas = async () => {
    // canvas size equal to image size (retina display)
    const img = await fabric.Image.fromURL(imageUrl, {}, {})
    const canvas = new fabric.Canvas(canvasNodeRef.current!, {
      backgroundImage: img,
    })
    canvas.setDimensions({ height: img.height, width: img.width }, { backstoreOnly: true })
    canvas.renderAll()
    canvasRef.current = canvas

    // zoom canvas to fit screen
    if (img.height > window.innerHeight) {
      const zoom = window.innerHeight / img.height
      canvas.setDimensions({ height: window.innerHeight, width: zoom * img.width }, { cssOnly: true })
      displayZoomWithUnit(zoom)
    }
    if (img.width > canvasWindowRef.current!.clientWidth) {
      const zoom = canvasWindowRef.current!.clientWidth / img.width
      canvas.setDimensions({ height: zoom * img.height, width: canvasWindowRef.current!.clientWidth }, { cssOnly: true })
      displayZoomWithUnit(zoom)
    }
  }

  const displayZoomWithUnit = (zoom: number) => {
    zoomInputRef.current!.value = `${(zoom * 100).toPrecision(4)}%`
  }

  const handleZoomChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const zoom = parseFloat(e.target.value) / 100

    const canvas = canvasRef.current!
    canvas.setDimensions({ height: canvas.height * zoom, width: canvas.width * zoom }, { cssOnly: true })
    displayZoomWithUnit(zoom)
  }

  const handleZoomEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      zoomInputRef.current?.blur()
    }
  }

  const handlePanZoom = (e: React.WheelEvent<HTMLDivElement> | any) => {
    if (!e.ctrlKey) return
    e.preventDefault()
    e.stopPropagation()

    const delta = e.deltaY
    let zoom = parseFloat(zoomInputRef.current!.value) / 100
    zoom *= 0.999 ** delta
    if (zoom > 20) zoom = 20
    if (zoom < 0.01) zoom = 0.01

    const canvas = canvasRef.current!
    canvas.setDimensions({ height: canvas.height * zoom, width: canvas.width * zoom }, { cssOnly: true })
    displayZoomWithUnit(zoom)
  }

  return (
    <>
      <div className='flex grow justify-center preview overflow-auto' ref={canvasWindowRef}>
        <canvas ref={canvasNodeRef} />
      </div>
      <div className='flex fixed bottom-0 w-full bg-base-200 h-[.8rem] opacity-70'>
        <input
          ref={zoomInputRef}
          onBlur={handleZoomChange}
          onKeyDown={handleZoomEnter}
          className='w-[75px] text-[12px] text-center focus:outline-none bg-slate-900 opacity-100'
          type='text'
          onChange={(e) => (zoomInputRef.current!.value = e.target.value)}
        />
        <span className='text-[10px] leading-[12px] ml-5'>{`770 px x 1080 px (72 ppi)`}</span>
      </div>
    </>
  )
}

export default ImageWindow

// tsboard/src/components/ImageWindow.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Application, Sprite, Assets } from 'pixi.js'
import sampleImage from '../assets/128.jpg'

let app: Application

const canvasWindow = ref<HTMLDivElement>()
const canvas = ref<HTMLCanvasElement>()
const zoom = ref(1)
const zoomIndicator = computed(() => `${(zoom.value * 100).toPrecision(4)}%`)

const zoomAspectRatio = (imageWidth: number, imageHeight: number, zoomFactor?: number): [number, number, number] => {
  const screenWidth = canvasWindow.value!.clientWidth
  const screenHeight = canvasWindow.value!.clientHeight
  // scale to the screen size by default
  zoomFactor = zoomFactor ?? Math.min(screenWidth / imageWidth, screenHeight / imageHeight, 1)
  zoomFactor = Math.min(Math.max(zoomFactor, 0.01), 10)
  return [Math.floor(imageWidth * zoomFactor), Math.floor(imageHeight * zoomFactor), zoomFactor]
}

const setZoomAndTransform = (value?: string | number) => {
  const inputZoom = typeof value == 'string' ? parseFloat(value) / 100 : value
  let [width, height, zoomFactor] = zoomAspectRatio(app.renderer.width, app.renderer.height, inputZoom)
  app.view.style!.width = `${width}px`
  app.view.style!.height = `${height}px`
  zoom.value = zoomFactor
}

const handlePanZoom = (e: WheelEvent) => {
  if (!e.ctrlKey) return
  e.preventDefault()
  e.stopPropagation()

  const delta = e.deltaY
  let zoomFactor = (0.999 ** delta) * zoom.value
  setZoomAndTransform(zoomFactor)
}

onMounted(async () => {
  const bgTexture = await Assets.load(sampleImage)

  // let the canvas equal to the image, like an actual "canvas"
  app = new Application({
    view: canvas.value!,
    width: bgTexture.width,
    height: bgTexture.height,
    // image scaled unexpectedly if resolution > 2, kept 1 for now
    resolution: 1,
    autoDensity: false,
  })

  const image = new Sprite(bgTexture)

  setZoomAndTransform()

  app.stage.addChild(image)
})
</script>

<template>
  <div class="flex grow overflow-auto preview" @wheel="handlePanZoom" ref="canvasWindow">
    <!-- https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container -->
    <div class="m-auto">
      <canvas ref="canvas"></canvas>
    </div>
  </div>
  <div class="flex sticky bottom-0 w-full bg-base-200 h-[1.2rem] leading-[1.2rem] opacity-70">
    <input
      ref="zoomInputRef"
      class="w-[75px] text-[12px] text-center focus:outline-none bg-slate-900 opacity-100"
      type="text"
      :value="zoomIndicator"
      @blur="setZoomAndTransform(($event.target as HTMLInputElement).value)"
      @keydown.enter="($event.target as HTMLInputElement).blur()"
    />
    <!-- @vue-skip -->
    <span class="text-[12px] px-5 bg-black">{{ `${canvas?.width} px x ${canvas?.height} px (${window.devicePixelRatio} dppx)` }}</span>
  </div>
</template>

<style scoped>
.preview {
  background-image: repeating-linear-gradient(
    45deg,
    hsl(var(--b1)),
    hsl(var(--b1)) 13px,
    hsl(var(--b2)) 13px,
    hsl(var(--b2)) 14px
  );
}
</style>
